defaults:
  run:
    working-directory: FAKE_WEBCOMIC

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: dotnet restore
      - run: dotnet build

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: dotnet test
      - run: dotnet build

  pack:
    runs-on: ubuntu-20.04
    steps:
      - run: dotnet publish

on: push
